/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = string;
export type ContentType = { 'video' : null } |
  { 'image' : null };
export interface CreateMemoryArgs {
  'media' : ExternalBlob,
  'title' : string,
  'contentType' : ContentType,
  'date' : string,
  'filename' : string,
  'story' : [] | [string],
  'category' : [] | [Category],
}
export type ExternalBlob = Uint8Array;
export interface Memory {
  'id' : MemoryId,
  'media' : ExternalBlob,
  'title' : string,
  'uploaderName' : string,
  'contentType' : ContentType,
  'date' : string,
  'filename' : string,
  'story' : [] | [string],
  'category' : [] | [Category],
  'uploader' : Principal,
  'uploadedAt' : Time,
}
export type MemoryId = bigint;
export type SortBy = { 'date' : null } |
  { 'category' : null };
export type Time = bigint;
export interface UpdateMemoryArgs {
  'id' : MemoryId,
  'title' : string,
  'date' : string,
  'story' : [] | [string],
  'category' : [] | [Category],
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createMemory' : ActorMethod<[CreateMemoryArgs], MemoryId>,
  'deleteMemory' : ActorMethod<[MemoryId], boolean>,
  'getMemory' : ActorMethod<[MemoryId], [] | [Memory]>,
  'listMemories' : ActorMethod<[SortBy], Array<Memory>>,
  'updateMemory' : ActorMethod<[UpdateMemoryArgs], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];