/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ContentType = IDL.Variant({
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const Category = IDL.Text;
export const CreateMemoryArgs = IDL.Record({
  'media' : ExternalBlob,
  'title' : IDL.Text,
  'contentType' : ContentType,
  'date' : IDL.Text,
  'filename' : IDL.Text,
  'story' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
});
export const MemoryId = IDL.Nat;
export const Time = IDL.Int;
export const Memory = IDL.Record({
  'id' : MemoryId,
  'media' : ExternalBlob,
  'title' : IDL.Text,
  'uploaderName' : IDL.Text,
  'contentType' : ContentType,
  'date' : IDL.Text,
  'filename' : IDL.Text,
  'story' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
  'uploader' : IDL.Principal,
  'uploadedAt' : Time,
});
export const SortBy = IDL.Variant({ 'date' : IDL.Null, 'category' : IDL.Null });
export const UpdateMemoryArgs = IDL.Record({
  'id' : MemoryId,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'story' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createMemory' : IDL.Func([CreateMemoryArgs], [MemoryId], []),
  'deleteMemory' : IDL.Func([MemoryId], [IDL.Bool], []),
  'getMemory' : IDL.Func([MemoryId], [IDL.Opt(Memory)], ['query']),
  'listMemories' : IDL.Func([SortBy], [IDL.Vec(Memory)], ['query']),
  'updateMemory' : IDL.Func([UpdateMemoryArgs], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ContentType = IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null });
  const Category = IDL.Text;
  const CreateMemoryArgs = IDL.Record({
    'media' : ExternalBlob,
    'title' : IDL.Text,
    'contentType' : ContentType,
    'date' : IDL.Text,
    'filename' : IDL.Text,
    'story' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
  });
  const MemoryId = IDL.Nat;
  const Time = IDL.Int;
  const Memory = IDL.Record({
    'id' : MemoryId,
    'media' : ExternalBlob,
    'title' : IDL.Text,
    'uploaderName' : IDL.Text,
    'contentType' : ContentType,
    'date' : IDL.Text,
    'filename' : IDL.Text,
    'story' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
    'uploader' : IDL.Principal,
    'uploadedAt' : Time,
  });
  const SortBy = IDL.Variant({ 'date' : IDL.Null, 'category' : IDL.Null });
  const UpdateMemoryArgs = IDL.Record({
    'id' : MemoryId,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'story' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createMemory' : IDL.Func([CreateMemoryArgs], [MemoryId], []),
    'deleteMemory' : IDL.Func([MemoryId], [IDL.Bool], []),
    'getMemory' : IDL.Func([MemoryId], [IDL.Opt(Memory)], ['query']),
    'listMemories' : IDL.Func([SortBy], [IDL.Vec(Memory)], ['query']),
    'updateMemory' : IDL.Func([UpdateMemoryArgs], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };